export DIR='syncNanoAOD/*.py'
grep -rl 'bpt_1'  $DIR | xargs sed -i 's/bpt_1/bpt_deepcsv_1/g'
grep -rl 'beta_1' $DIR | xargs sed -i 's/beta_1/beta_deepcsv_1/g'
grep -rl 'bphi_1' $DIR | xargs sed -i 's/bphi_1/bphi_deepcsv_1/g'
grep -rl 'bm_1' $DIR | xargs sed -i 's/bm_1/bm_deepcsv_1/g'
grep -rl 'bdeepcsv_1' $DIR | xargs sed -i 's/bdeepcsv_1/bscore_deepcsv_1/g'
grep -rl 'bhadronflavour_1' $DIR | xargs sed -i 's/bhadronflavour_1/bflavour_deepcsv_1/g'

grep -rl 'bpt_2'  $DIR | xargs sed -i 's/bpt_2/bpt_deepcsv_2/g'
grep -rl 'beta_2' $DIR | xargs sed -i 's/beta_2/beta_deepcsv_2/g'
grep -rl 'bphi_2' $DIR | xargs sed -i 's/bphi_2/bphi_deepcsv_2/g'
grep -rl 'bm_2' $DIR | xargs sed -i 's/bm_2/bm_deepcsv_2/g'
grep -rl 'bdeepcsv_2' $DIR | xargs sed -i 's/bdeepcsv_2/bscore_deepcsv_2/g'
grep -rl 'bhadronflavour_2' $DIR | xargs sed -i 's/bhadronflavour_2/bflavour_deepcsv_2/g'

grep -rl 'bpt_flav_1'  $DIR | xargs sed -i 's/bpt_flav_1/bpt_deepflavour_1/g'
grep -rl 'beta_flav_1' $DIR | xargs sed -i 's/beta_flav_1/beta_deepflavour_1/g'
grep -rl 'bphi_flav_1' $DIR | xargs sed -i 's/bphi_flav_1/bphi_deepflavour_1/g'
grep -rl 'bm_flav_1' $DIR | xargs sed -i 's/bm_flav_1/bm_deepflavour_1/g'
grep -rl 'bdeepflav_1' $DIR | xargs sed -i 's/bdeepflav_1/bscore_deepflavour_1/g'
grep -rl 'bhadronflavour_flav_1' $DIR | xargs sed -i 's/bhadronflavour_flav_1/bflavour_deepflavour_1/g'

grep -rl 'bpt_flav_2'  $DIR | xargs sed -i 's/bpt_flav_2/bpt_deepflavour_2/g'
grep -rl 'beta_flav_2' $DIR | xargs sed -i 's/beta_flav_2/beta_deepflavour_2/g'
grep -rl 'bphi_flav_2' $DIR | xargs sed -i 's/bphi_flav_2/bphi_deepflavour_2/g'
grep -rl 'bm_flav_2' $DIR | xargs sed -i 's/bm_flav_2/bm_deepflavour_2/g'
grep -rl 'bdeepflav_2' $DIR | xargs sed -i 's/bdeepflav_2/bscore_deepflavour_2/g'
grep -rl 'bhadronflavour_flav_2' $DIR | xargs sed -i 's/bhadronflavour_flav_2/bflavour_deepflavour_2/g'
